SeguimientoEgresados/Areas/About/Controllers/InicioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SeguimientoEgresados.Services;

namespace SeguimientoEgresados.Areas.About.Controllers
{
    [Area("About")]
    public class InicioController : Controller
    {
        private readonly INotificacionesService _notificaciones;
        
        public InicioController(INotificacionesService notificaciones)
        {
            _notificaciones = notificaciones;
        }
        
        public async Task<IActionResult> Index()
        {
            await _notificaciones.VerificarCuestionario(User, HttpContext, ViewData, false);
            return View();
        }
    }
}

SeguimientoEgresados/Areas/BolsaDeTrabajo/Controllers/InicioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SeguimientoEgresados.Models;
using SeguimientoEgresados.Models.ViewModels;
using SeguimientoEgresados.Services;
using SeguimientoEgresados.Utils;

namespace SeguimientoEgresados.Areas.BolsaDeTrabajo.Controllers
{
    [Area("BolsaDeTrabajo")]
    public class InicioController : Controller
    {
        private readonly SeguimientoEgresadosContext _context;
        private readonly INotificacionesService _notificaciones;
        private readonly ICloudinaryService _cloudinary;
        
        public InicioController(SeguimientoEgresadosContext context, INotificacionesService notificaciones, ICloudinaryService cloudinary)
        {
            _context = context;
            _notificaciones = notificaciones;
            _cloudinary = cloudinary;
        }
        
        public async Task<IActionResult> Index()
        {
            ViewData["carreras"] = new SelectList(_context.Carreras, "Id", "Nombre");
            await _notificaciones.VerificarCuestionario(User, HttpContext, ViewData, false);
            return View();
        }
        
        [HttpGet]
        public async Task<IActionResult> GetVacantes(string ordenTabla, string busqueda, string filtroActual, int? pagina)
        {
            ViewData["OrdenActual"] = ordenTabla;
            ViewData["NombreSort"] = String.IsNullOrEmpty(ordenTabla) ? "nombre_desc" : "";
            ViewData["RepSort"] = ordenTabla == "rep_desc" ? "rep_asc" : "fecha_desc";
            ViewData["RegSort"] = ordenTabla == "fecha_desc" ? "fecha_asc" : "fecha_desc";
            
            if (busqueda != null)
            {
                pagina = 1;
            }
            else
            {
                //busqueda = filtroActual;
            }
            
            ViewData["Busqueda"] = busqueda;

            var query =
                    from vacante in _context.Vacantes
                    join empresa in _context.Empresas on vacante.IdEmpresa equals empresa.Id into vacantesEmpresa
                    from vacanteEmpresa in vacantesEmpresa.DefaultIfEmpty()
                    join usuario in _context.Usuarios on vacanteEmpresa.IdUsuario equals usuario.Id into usuariosVacanteEmpresa
                    from usuarioVacanteEmpresa in usuariosVacanteEmpresa.DefaultIfEmpty()
                    where usuarioVacanteEmpresa.Verificado != null && usuarioVacanteEmpresa.Verificado.Equals("true")
                    select new VerVacanteViewModel()
                    {
                        NombreEmpresa = vacanteEmpresa.Nombre,
                        Titulo = vacante.Titulo,
                        Descripcion = vacante.Descripcion,
                        Funciones = vacante.Funciones,
                        Requisitos = vacante.Requisitos,
                        Ofertas = vacante.Ofertas,
                        TipoContrato = vacante.TipoContrato,
                        Modalidad = vacante.Modalidad,
                        Horario = vacante.Horario,
                        Fecha = vacante.Fecha,
                        Id = vacante.Id,
                        LogoEmpresa = usuarioVacanteEmpresa.UrlImg,
                        Convenio = vacanteEmpresa.IdConvenio != null
                    };

            // var query =
            //     from vacante in _context.Vacantes
            //     join empresa in _context.Empresas on vacante.IdEmpresa equals empresa.Id into vacantesEmpresa
            //     from vacanteEmpresa in vacantesEmpresa.DefaultIfEmpty()
            //     select new VerVacanteViewModel()
            //     {
            //         NombreEmpresa = vacanteEmpresa.Nombre,
            //         Titulo = vacante.Titulo,
            //         Descripcion = vacante.Descripcion,
            //         Funciones = vacante.Funciones,
            //         Requisitos = vacante.Requisitos,
            //         Ofertas = vacante.Ofertas,
            //         TipoContrato = vacante.TipoContrato,
            //         Modalidad = vacante.Modalidad,
            //         Horario = vacante.Horario,
            //         Fecha = vacante.Fecha,
            //         Id = vacante.Id,
            //         LogoEmpresa = _context.Usuarios.FirstOrDefault(u => u.Id.Equals(vacanteEmpresa.IdUsuario))?.UrlImg
            //     };
            
            
            if (!string.IsNullOrEmpty(busqueda))
            {
                query = query.Where(v => v.NombreEmpresa.Contains(busqueda)
                                         || v.Titulo.Contains(busqueda)
                                         || v.Descripcion.Contains(busqueda)
                                         || v.Modalidad.Contains(busqueda)
                                         || v.TipoContrato.Contains(busqueda)
                                         || v.Ofertas.Contains(busqueda));
            }

            switch (ordenTabla)
            {
                case "nombre_desc":
                    query = query.OrderByDescending(e => e.Titulo);
                    break;
                case "fecha_desc":
                    query = query.OrderByDescending(e => e.Fecha);
                    break;
                case "fecha_asc":
                    query = query.OrderBy(e => e.Fecha);
                    break;
                case "rep_desc":
                    query = query.OrderByDescending(e => e.NombreEmpresa);
                    break;
                case "rep_asc":
                    query = query.OrderBy(e => e.NombreEmpresa);
                    break;
                default:
                    query = query.OrderBy(e => e.Titulo);
                    break;
            }

            int pageSize = 10;
            return PartialView("_GetVacantes",  await ListaPaginada<VerVacanteViewModel>.CreateAsync(query.AsNoTracking(), pagina ?? 1, pageSize));
        }

        public async Task<IActionResult> VerDetallesVacante(int id)
        {
            var query =
                from vacante in _context.Vacantes
                join empresa in _context.Empresas on vacante.IdEmpresa equals empresa.Id into vacantesEmpresa
                from vacanteEmpresa in vacantesEmpresa.DefaultIfEmpty()
                where  vacante.Id.Equals(id)
                select new VerVacanteViewModel()
                {
                    NombreEmpresa = vacanteEmpresa.Nombre,
                    Titulo = vacante.Titulo,
                    Descripcion = vacante.Descripcion,
                    Funciones = vacante.Funciones,
                    Requisitos = vacante.Requisitos,
                    Ofertas = vacante.Ofertas,
                    TipoContrato = vacante.TipoContrato,
                    Modalidad = vacante.Modalidad,
                    Horario = vacante.Horario,
                    Fecha = vacante.Fecha,
                    Id = vacante.Id,
                    //LogoEmpresa = usuarioVacanteEmpresa.UrlImg,
                    Convenio = vacanteEmpresa.IdConvenio != null
                };
            return PartialView("_DetallesVacante", await query.FirstOrDefaultAsync());
        }
        
        public async Task<IActionResult> Postula(int id){
            
            var email = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.Email)?.Value;

            if (email == null)
                return Ok();
            
            Models.Usuario? user = await _context.Usuarios.FirstOrDefaultAsync(u => u.Email.Equals(email));
            Egresado egresado = await _context.Egresados.FirstOrDefaultAsync(e => e.IdUsuario.Equals(user.Id));
            
            var query =
                from vacante in _context.Vacantes
                join empresa in _context.Empresas on vacante.IdEmpresa equals empresa.Id into vacantesEmpresa
                from vacanteEmpresa in vacantesEmpresa.DefaultIfEmpty()
                where  vacante.Id.Equals(id)
                select new VerVacanteViewModel()
                {
                    NombreEmpresa = vacanteEmpresa.Nombre,
                    Titulo = vacante.Titulo,
                    Descripcion = vacante.Descripcion,
                    Funciones = vacante.Funciones,
                    Requisitos = vacante.Requisitos,
                    Ofertas = vacante.Ofertas,
                    TipoContrato = vacante.TipoContrato,
                    Modalidad = vacante.Modalidad,
                    Horario = vacante.Horario,
                    Fecha = vacante.Fecha,
                    Id = vacante.Id,
                    IdEmpresa = vacante.IdEmpresa,
                    //LogoEmpresa = usuarioVacanteEmpresa.UrlImg,
                    Convenio = vacanteEmpresa.IdConvenio != null
                };
            
            VerVacanteViewModel vacanteO = await query.AsNoTracking().FirstOrDefaultAsync();

            if (vacanteO == null)
                return NotFound();
            
            //Postulante postulante = 
            //    from postulante in _context.Postulantes
                // join vacantee in _context.Vacantes on postulante.IdVacante equals vacantee.Id into matches
                // from match in matches.DefaultIfEmpty()
                //     join 

            Postulante postulante = await _context.Postulantes.FirstOrDefaultAsync(p =>
                    p.IdVacante.Equals(vacanteO.Id) && p.IdEgresado.Equals(egresado.Id));

            ViewData["postulado"] = postulante != null;
             
            return View(vacanteO);
        }

        [Authorize(Roles = "Egresado")]

SeguimientoEgresados/Areas/Egresados/Controllers/InicioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SeguimientoEgresados.Models;
using SeguimientoEgresados.Models.ViewModels;
using SeguimientoEgresados.Services;
using SeguimientoEgresados.Utils;

namespace SeguimientoEgresados.Areas.Egresados.Controllers
{
    [Area("Egresados")]
    public class InicioController : Controller
    {
        private Models.Usuario _usuario;

        private readonly SeguimientoEgresadosContext _context;
        private readonly INotificacionesService _notificaciones;
        
        public InicioController(SeguimientoEgresadosContext context, INotificacionesService notificaciones)
        {
            _context = context;
            _notificaciones = notificaciones;
        }
        
        [HttpGet, Route("~/Egresados/")]
        public async Task<IActionResult> Index()
        {
            ViewData["carreras"] = new SelectList(_context.Carreras, "Id", "Nombre");
            
            await _notificaciones.VerificarCuestionario(User, HttpContext, ViewData, false);
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> _GetEgresados()
        {
            var egresadosCarrera = _context.Egresados.Include(c => c.IdCarreraNavigation).AsNoTracking();
            
            var egresados =
                from egresado in egresadosCarrera
                join usuario in _context.Usuarios on egresado.IdUsuario equals usuario.Id into matches
                from match in matches
                select new EgresadoPublicoViewModel()
                {
                    Carrera = egresado.IdCarreraNavigation.Nombre,
                    Nombres = match.Nombre,
                    ApeM = match.ApellidoMaterno,
                    ApeP = match.ApellidoPaterno,
                    NoControl = egresado.NControl,
                    FechaInicio = egresado.FechaInicio,
                    FechaFin = egresado.FechaEgreso
                };

            return PartialView(await ListaPaginada<EgresadoPublicoViewModel>.CreateAsync(egresados.AsNoTracking(), 1, 100));
        }
    }
}

SeguimientoEgresados/Areas/Empleadores/Controllers/InicioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SeguimientoEgresados.Models;
using SeguimientoEgresados.Models.ViewModels;
using SeguimientoEgresados.Services;

namespace SeguimientoEgresados.Areas.Empleadores.Controllers
{
    [Area("Empleadores")]
    public class InicioController : Controller
    {
        private readonly SeguimientoEgresadosContext _db;
        private readonly INotificacionesService _notificaciones;
        
        public InicioController(SeguimientoEgresadosContext db, INotificacionesService notificaciones)
        {
            _db = db;
            _notificaciones = notificaciones;
        }
        
        // [HttpGet, Route("~/Empleadores/")]
        public async Task<IActionResult> Index()
        {
            var query =
                from empresa in _db.Empresas
                join usuario in _db.Usuarios on empresa.IdUsuario equals usuario.Id into empresasUsuario
                from empresaUsuario in empresasUsuario.DefaultIfEmpty()
                where empresaUsuario.Verificado != null && empresaUsuario.Verificado.Equals("true")
                select new VisitaEmpresaViewModel(empresaUsuario.Id, empresa.Id)
                {
                    Nombre = empresa.Nombre,
                    Descripcion = empresa.Descripcion,
                    Correo = empresa.CorreoEmpresa,
                    Telefono = empresa.Telefono,
                    Website = empresa.Website,
                    Rfc = empresa.Rfc,
                    FechaRegistro = empresaUsuario.Fecha,
                    NombreRep = empresaUsuario.Nombre,
                    Ape1Rep = empresaUsuario.ApellidoPaterno,
                    Ape2Rep = empresaUsuario.ApellidoMaterno,
                    LogoImagen = empresaUsuario.UrlImg,
                    Convenio = empresa.IdConvenio != null
                };

            query = query.OrderBy(e => e.Nombre);
            
            await _notificaciones.VerificarCuestionario(User, HttpContext, ViewData, false);
            return View(await query.AsNoTracking().ToListAsync());
        }
    }
}

SeguimientoEgresados/Areas/Galeria/Controllers/InicioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SeguimientoEgresados.Models;
using SeguimientoEgresados.Models.ViewModels;
using SeguimientoEgresados.Services;

namespace SeguimientoEgresados.Areas.Galeria.Controllers
{
    [Area("Galeria")]
    public class InicioController : Controller
    {
        private readonly SeguimientoEgresadosContext _db;
        private readonly INotificacionesService _notificaciones;
        
        public InicioController(SeguimientoEgresadosContext db, INotificacionesService notificaciones)
        {
            _db = db;
            _notificaciones = notificaciones;
        }
        
        public async Task<IActionResult> Index()
        {
            await _notificaciones.VerificarCuestionario(User, HttpContext, ViewData, false);

            var query = from galeria in _db.Galeria select new VerAlbumViewModel()
            {
                Id = galeria.Id,
                Descripcion = galeria.Descripcion,
                Nombre = galeria.Nombre,
                Fecha = galeria.Fecha
            };
            
            List<VerAlbumViewModel> albumes = await query.ToListAsync();
            for (int i = 0; i < albumes.Count; i++)
            {
                ImagenGalerium algunaImagen = await _db.ImagenGaleria.FirstOrDefaultAsync(img => img.IdAlbum.Equals(albumes[i].Id));
                albumes[i].MiniaturaUrl = algunaImagen.Url;

            }
            
            return View(albumes);
        }

        public async Task<IActionResult> _VerAlbum(int id)
        {
            var album = await _db.Galeria.FirstOrDefaultAsync(g => g.Id.Equals(id));
            return View(album);
        }

        public async Task<IActionResult> GetImagenes(int idGaleria)
        {
            var query = from img in _db.ImagenGaleria where img.IdAlbum.Equals(idGaleria) select img;

            return Json(await query.AsNoTracking().ToListAsync());
        }
    }
}

SeguimientoEgresados/Views/Inicio/Index.cshtml
@using SeguimientoEgresados.Controllers
@model Usuario

@{
    //Layout = "_Layout";
    ViewData["Title"] = "Página de inicio";
}
<section class="container">
    <div class="main-container d-flex justify-content-center align-items-center animate__animated animate__delay-1s animate__fadeIn">
        <article class="row">
            <div class="col-md-6">
                <h1>Seguimiento de egresados</h1>
                <p>Instituto Tecnológico de México</p>
                <p>Campus Cuautla</p>
            </div>
            <div class="cont-img col-md-6 animate__animated animate__fast animate__fadeIn">
                <img class="cont-img-c img-fluid" src="~/images/Mancha.png" alt="Imagen de inicio"/>
                <img id="img-inicio" class="cont-img-c img-fluid" src="~/images/licenciatura2.png" alt="Imagen de inicio"/>
            </div>
            <div class="col-md-6 row mt-3">
                @if(!User.Identity.IsAuthenticated){
                <div class="col-12 col-sm-6 col-md-12 col-lg-6 mb-2">
                    <a asp-area="" asp-controller="Registro" asp-action="Index" class="btn btn-primary w-100">Unirse al programa<i class="fa-solid fa-file-pen ms-2"></i></a>
                </div>
                <div class="col-12 col-sm-6 col-md-12 col-lg-6">
                    <a asp-area="About" asp-controller="Inicio" asp-action="Index" class="btn btn-outline-secondary w-100">Más información</a>
                </div>
                }
                else
                {
                    <div class="col-12 col-sm-8 col-md-12 col-lg-8">
                        <a asp-area="About" asp-controller="Inicio" asp-action="Index" class="btn btn-outline-secondary w-100">Más información</a>
                    </div>
                }
            </div>
        </article>
    </div>
    
    @* <div class="separador-inicio"></div> *@
    <article id="tarejtas" class="row justify-content-evenly animate__animated animate__delay-1s animate__fadeIn">
        <div class="col-md-6 col-lg-4 col-xl-3 row mb-3 mt-3">
            <div class="bg-white col-12 col-sm-6 col-md-10 col-lg-12 tarjeta-inicio container rounded p-4">
                <div class="row justify-content-center">
                    <div class="icono-tarjeta col-12 mb-3 rounded-circle text-white d-flex justify-content-center align-items-center">
                        <i class="fa-solid fa-graduation-cap fa-xl"></i>
                    </div>
                    <h3>Egresados</h3>
                    <p>
                        Estudiante que ha concluido
                        sus estudios y posee un 
                        título
                    </p>
                </div>
            </div>
        </div>
        <div class="col-md-6 col-lg-4 col-xl-3 row mb-3 mt-md-3">
            <div class="bg-light col-12 col-sm-6 col-md-10 col-lg-12 tarjeta-inicio container rounded p-4">
                <div class="row justify-content-center">
                    <div class="icono-tarjeta col-12 mb-3 rounded-circle text-white d-flex justify-content-center align-items-center">
                        <i class="fa-solid fa-briefcase fa-xl"></i>
                    </div>
                    <h3>Empleador</h3>
                    <p>
                        Persona que pueda proporcionar
                        información acerca de su empresa
                        y empleos disponibles
                    </p>
                </div>
            </div>
        </div>
        <div class="col-md-6 col-lg-4 col-xl-3 row mb-3 mt-md-3">
            <div class="bg-white col-12 col-sm-6 col-md-10 col-lg-12 tarjeta-inicio container rounded p-4">
                <div class="row justify-content-center">
                    <div class="icono-tarjeta col-12 mb-3 rounded-circle text-white d-flex justify-content-center align-items-center">
                        <i class="fa-solid fa-sack-dollar fa-xl"></i>
                    </div>
                    <h3>Bolsa de trabajo</h3>
                    <p>
                        Compilación de empleos
                        proporcionados por los empleadores
                    </p>
                </div>
            </div>
        </div>
    </article>
    
    <div class="main-container d-flex justify-content-center align-items-center">
        <article class="row">
            <div class="col-md-8">
                <h1>¿Qué es el seguimiento de egresados?</h1>
                <p>El seguimiento de egresados es un procedimiento que permite a la 
                    institución educativa conocer las actividades profesionales de sus 
                    egresadis en el mercado de trabajo, así como la calidad de la 
                    formación académica que éstos recibieron.</p>
                <a asp-area="About" asp-controller="Inicio" asp-action="Index" class="text-decoration-none">Más<i class="fa-solid fa-angle-right ms-2"></i></a>
            </div>
            <div class="col-10 col-md-4 m-auto animate__animated animate__fast animate__fadeIn">
                <img class="img-fluid" src="~/images/licenciatura2.png" alt="Imagen de inicio"/>
            </div>
            @* <div class="col-md-6 row mt-3"> *@
            @*     $1$ <div class="col-12 col-sm-6 col-md-12 col-lg-6 mb-2"> #1# *@
            @*     $1$     <button class="btn btn-primary w-100">Unirse al programa</button> #1# *@
            @*     $1$ </div> #1# *@
            @*     $1$ <div class="col-12 col-sm-6 col-md-12 col-lg-6"> #1# *@
            @*     $1$     <button href="#tarjetas" class="btn btn-outline-secondary w-100">Más información</button> #1# *@
            @*     $1$ </div> #1# *@
            @* </div> *@
        </article>
    </div>
</section>

SeguimientoEgresados/Views/Inicio/_EsperaReporte.cshtml
<!-- Modal -->
<div class="modal fade" id="modalReporte" data-bs-backdrop="static" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
        <div id="reportForm" class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel"><i class="fa-solid fa-clock me-2"></i>Espera de reporte</h5>
            </div>
            <div class="modal-body">
                <p>Los visitantes sólo pueden realizar un reporte por sección del sitio web, debe esperar un tiempo para poder volver a reportar en esta sección.</p>
                <p>Gracias por su comprensión.</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-bs-dismiss="modal"><i class="fa-solid fa-thumbs-up me-2"></i>Entendido</button>
            </div>
        </div>
    </div>
</div>

SeguimientoEgresados/Views/Inicio/_RealizarReporte.cshtml
<!-- Modal -->
<div class="modal fade" id="modalReporte" data-bs-backdrop="static" tabindex="-1" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
    <form id="reportForm" class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Reporte de fallo, sugerencia o queja</h5>
      </div>
      <div class="modal-body">
        <div class="container">
          <div class="row">
            <div class="col-12 mb-3">
              <div class="form-floating">
                <input type="text" name="titulo" class="form-control" id="tituloReporte" placeholder="Título de fallo, sugerencia o queja" required>
                <label for="tituloReporte"><i class="fa-solid fa-heading me-2"></i>Título del fallo, sugerencia o queja</label>
              </div>
            </div>
            <div class="col-12">
              <label for="descripcionReporte" class="form-label"><i class="fa-solid fa-circle-info me-2"></i>Detalles del fallo, sugerencia o queja</label>
              <textarea name="descripcion" class="form-control" id="descripcionReporte" rows="5" required></textarea>
            </div>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="reset" class="btn btn-outline-danger" data-bs-dismiss="modal"><i class="fa-solid fa-xmark me-2" id="btn-cancel"></i>Cancelar</button>
        <button type="submit" class="btn btn-primary"><i class="fa-solid fa-paper-plane me-2"></i>Realizar reporte</button>
      </div>
    </form>
  </div>
</div>